---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: true
  no_log: "{{ molecule_no_log }}"
  vars:
    ssh_port: 22

    # Lifecycle management
    resource_ttl_hours: 4  # Resources should be cleaned up after 4 hours

    security_group_name: molecule
    security_group_description: Security group for testing Molecule
    security_group_rules:
      - proto: tcp
        from_port: "{{ ssh_port }}"
        to_port: "{{ ssh_port }}"
        cidr_ip: '0.0.0.0/0'
      - proto: icmp
        from_port: 8
        to_port: -1
        cidr_ip: '0.0.0.0/0'
    security_group_rules_egress:
      - proto: -1
        from_port: 0
        to_port: 0
        cidr_ip: '0.0.0.0/0'

    key_pair_name: molecule_key
    key_pair_path: "{{ lookup('env', 'MOLECULE_EPHEMERAL_DIRECTORY') }}/ssh_key"
  tasks:
    - name: Set lifecycle timestamps
      set_fact:
        deployed_time: "{{ ansible_date_time.iso8601 }}"
        cleanup_time: "{{ '%Y-%m-%dT%H:%M:%SZ' | strftime((ansible_date_time.epoch | int) + (resource_ttl_hours | int * 3600)) }}"

    - name: Create security groups
      amazon.aws.ec2_security_group:
        vpc_id: "{{ item.vpc_id }}"
        name: "{{ security_group_name }}"
        description: "{{ security_group_name }}"
        rules: "{{ security_group_rules }}"
        rules_egress: "{{ security_group_rules_egress }}"
        tags:
          Name: "{{ security_group_name }}"
          ManagedBy: "Molecule"
          Purpose: "Testing"
          Project: "ansible-declarative-access"
          Environment: "CI"
          CreatedBy: "GitHub-Actions"
          DeployedTime: "{{ deployed_time }}"
          CleanupTime: "{{ cleanup_time }}"
          TTL: "{{ resource_ttl_hours }}h"
      loop: "{{ molecule_yml.platforms }}"
      run_once: true

    - name: Test for presence of local key pair
      stat:
        path: "{{ key_pair_path }}"
      register: key_pair_local

    - name: Delete remote key pair
      amazon.aws.ec2_key:
        name: "{{ key_pair_name }}"
        state: absent
      when: not key_pair_local.stat.exists

    - name: Create key pair
      amazon.aws.ec2_key:
        name: "{{ key_pair_name }}"
      register: key_pair

    - name: Persist the key pair
      copy:
        dest: "{{ key_pair_path }}"
        content: "{{ key_pair.key.private_key }}"
        mode: 0600
      when: key_pair.changed

    - name: Get the ec2 ami(s) by owner and name, if image not set
      amazon.aws.ec2_ami_info:
        owners: "{{ item.image_owner }}"
        filters:
          name: "{{ item.image_name }}"
      loop: "{{ molecule_yml.platforms }}"
      when:
        - item.image is not defined
        - item.image_id is not defined
        - item.image_name is defined
      register: ami_info

    - name: Create molecule instance(s)
      amazon.aws.ec2_instance:
        key_name: "{{ key_pair_name }}"
        image_id: >-
          {{ item.image_id
          if item.image_id is defined
          else (item.image if item.image is defined
          else (ami_info.results[index].images | sort(attribute='creation_date', reverse=True))[0].image_id) }}
        instance_type: "{{ item.instance_type }}"
        vpc_subnet_id: "{{ item.vpc_subnet_id }}"
        security_groups: ["{{ security_group_name }}"]
        tags:
          Name: >-
            {{ item.instance_tags.Name
            if item.instance_tags is defined and item.instance_tags.Name is defined
            else 'molecule-' ~ item.name }}
          instance: "{{ item.name }}"
          ManagedBy: "Molecule"
          Purpose: "Testing"
          Project: "ansible-declarative-access"
          Environment: "CI"
          CreatedBy: "GitHub-Actions"
          DeployedTime: "{{ deployed_time }}"
          CleanupTime: "{{ cleanup_time }}"
          TTL: "{{ resource_ttl_hours }}h"
        network:
          assign_public_ip: true
        wait: true
        state: running
      register: server
      loop: "{{ molecule_yml.platforms }}"
      loop_control:
        index_var: index
      async: 7200
      poll: 0

    - name: Wait for instance(s) creation to complete
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: ec2_jobs
      until: ec2_jobs.finished
      retries: 300
      with_items: "{{ server.results }}"

    # Mandatory configuration for Molecule to function.

    - name: Populate instance config dict
      set_fact:
        instance_conf_dict: {
          'instance': "{{ item.instances[0].tags.instance }}",
          'address': "{{ item.instances[0].public_ip_address }}",
          'user': "{{ 'ubuntu' if 'ubuntu' in item.instances[0].tags.instance else 'ec2-user' }}",
          'port': "{{ ssh_port }}",
          'identity_file': "{{ key_pair_path }}",
          'instance_ids': "{{ item.instance_ids }}", }
      with_items: "{{ ec2_jobs.results }}"
      register: instance_config_dict
      when: server.changed | bool

    - name: Convert instance config dict to a list
      set_fact:
        instance_conf: "{{ instance_config_dict.results | map(attribute='ansible_facts.instance_conf_dict') | list }}"
      when: server.changed | bool

    - name: Dump instance config
      copy:
        content: "{{ instance_conf | to_json | from_json | to_yaml }}"
        dest: "{{ molecule_instance_config }}"
      when: server.changed | bool

    - name: Wait for SSH
      wait_for:
        port: "{{ ssh_port }}"
        host: "{{ item.address }}"
        search_regex: SSH
        delay: 10
        timeout: 320
      with_items: "{{ lookup('file', molecule_instance_config) | from_yaml }}"

    - name: Wait for boot process to finish
      pause:
        minutes: 2
